### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [treyssatvincent/carriage-return.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by treyssatvincent** [comment]
Added in the README: https://github.com/treyssatvincent/carriage-return.zsh-theme/tree/main#readme
